nelmio_api_doc:
    documentation:
        servers:
          - url: http://127.0.0.1:8000
        info:
            title: Serial Lovers API
            description: Routes api
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
