gesdinet_jwt_refresh_token:
  path: /api/refresh_token

controllers:
    resource: ../src/Controller/
    type: attribute


api_login_check:
  path: /api/login

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
