api_login_check:
  path: /api/login

gesdinet_jwt_refresh_token:
  path: /api/refresh_token
  controller: gesdinet.jwtrefreshtoken::refresh

controllers:
    resource: ../src/Controller/
    type: attribute

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
