name: ci-web

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci-web:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./web
        run: bun install

      - name: Check typing
        working-directory: ./web
        run: bun type-check

      - name: Lint
        working-directory: ./web
        run: bun lint

      - name: Build application
        working-directory: ./web
        run: bun run build

      - name: Run tests
        working-directory: ./web
        run: bun jest

      - name: Install Playwright Browsers
        working-directory: ./web
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./web
        run: bun playwright

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30
